### PR TITLE
Allow two different pipelines

### PR DESCRIPTION
**Pull request by robertmaynard**
Warning: This will break any `catalyst.py` that you currently have!

This allows a catalyst python plugin script to specify if it should use the contour (still no clipping) or the slice pipeline. 

The way to control which pipeline we should use is to specify the pipelinemode variable

```
#1 == Contour, 2 == Slice
pipelinemode = 2
self._data = self.catalyst.CatalystInitialize(c_hostname,
                                                      c_int(int(port)),
                                                      c_outputfile,
                                                      pipelinemode,
                                                      self._catalystData)
```

Lastly to specify the slice planes that you wish you would use the following code ( 4 slice planes, 0.25 spaced apart )

```
        origin = (c_float *3)()
        normal = (c_float *3)()
        origin[0] = .0
        origin[1] = .0
        origin[2] = .0
        normal[0] = 1.
        normal[1] = .0
        normal[2] = .0
        self.catalyst.CatalystSetSlicePlanes( origin,normal,4,c_double(0.25) )
```

### CODE REVIEW

**Comment by robertmaynard** [comment]
Note that this is based on MR #4 

@iyer-arvind  @tfogal

**Comment by iyer-arvind** [comment]
This is currently giving me segfaults. After setting the pipeline_mode, are any other parameters not having a good default value?  Do I absolutely need to set the slice planes, the contour_by,  color_by etc  or are they defaulted to some sane values?

**Comment by robertmaynard** [comment]
They should all have defaults that don't cause a segfault. Are you setting the pipeline mode to 1 or 2?

**Comment by iyer-arvind** [comment]
Today the segfault issues have mysteriously vanished.  I think it must have been some bad memory issue. Q contours are not yet visible. I think it may be the Gradient calculation (MR#6)  issue, I am trying to merge both and try.

**Comment by iyer-arvind** [comment]
Can we close this in favor of #7 ?

**Comment by robertmaynard** [comment]
Yes we can

**Pull request closed without merging**
